//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNet.Common.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCNet.Common.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfServiceItem xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ServiceItem&gt;
        ///    &lt;ServiceName&gt;Test&lt;/ServiceName&gt;
        ///    &lt;DisplayName&gt;Test Service&lt;/DisplayName&gt;
        ///    &lt;BinaryPathName&gt;G:\test.exe&lt;/BinaryPathName&gt;
        ///    &lt;TargetFramework&gt;Net35&lt;/TargetFramework&gt;
        ///  &lt;/ServiceItem&gt;
        ///&lt;/ArrayOfServiceItem&gt;.
        /// </summary>
        internal static string BeginInstalledServicesXmlFile {
            get {
                return ResourceManager.GetString("BeginInstalledServicesXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:&gt;sc qc WindowsService1
        ///[SC] QueryServiceConfig SUCCESS
        ///
        ///SERVICE_NAME: WindowsService1
        ///        TYPE               : 10  WIN32_OWN_PROCESS
        ///        START_TYPE         : 3   DEMAND_START
        ///        ERROR_CONTROL      : 1   NORMAL
        ///        BINARY_PATH_NAME   : &quot;D:\Mailbox\CCNet.Extensions\CCNet.Common.Test\bin\Debug\TestWindowsService.exe&quot;
        ///        LOAD_ORDER_GROUP   :
        ///        TAG                : 0
        ///        DISPLAY_NAME       : [Test] Windows Service #1
        ///        DEPENDENCIES       :
        ///        SERVICE_START [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScQcWindowsService1Output {
            get {
                return ResourceManager.GetString("ScQcWindowsService1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:&gt;sc qc wudfsvc
        ///[SC] QueryServiceConfig SUCCESS
        ///
        ///SERVICE_NAME: wudfsvc
        ///        TYPE               : 20  WIN32_SHARE_PROCESS
        ///        START_TYPE         : 2   AUTO_START
        ///        ERROR_CONTROL      : 1   NORMAL
        ///        BINARY_PATH_NAME   : C:\Windows\system32\svchost.exe -k LocalSystemNetworkRestricted
        ///        LOAD_ORDER_GROUP   : PlugPlay
        ///        TAG                : 0
        ///        DISPLAY_NAME       : Windows Driver Foundation - User-mode Driver Framework
        ///        DEPENDENCIES       : PlugPlay
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScQcWudfsvcOutput {
            get {
                return ResourceManager.GetString("ScQcWudfsvcOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE_NAME: TermService
        ///DISPLAY_NAME: Terminal Services
        ///        TYPE               : 20  WIN32_SHARE_PROCESS
        ///        STATE              : 4  RUNNING
        ///                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        ///        WIN32_EXIT_CODE    : 0  (0x0)
        ///        SERVICE_EXIT_CODE  : 0  (0x0)
        ///        CHECKPOINT         : 0x0
        ///        WAIT_HINT          : 0x0
        ///
        ///SERVICE_NAME: Themes
        ///DISPLAY_NAME: Themes
        ///        TYPE               : 20  WIN32_SHARE_PROCESS
        ///        STATE              : 4  RU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScQueryOutput {
            get {
                return ResourceManager.GetString("ScQueryOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfServiceItem xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ServiceItem&gt;
        ///    &lt;ServiceName&gt;WindowsService1&lt;/ServiceName&gt;
        ///    &lt;DisplayName&gt;[Test] Windows Service #1&lt;/DisplayName&gt;
        ///    &lt;BinaryPathName&gt;{0}&lt;/BinaryPathName&gt;
        ///    &lt;TargetFramework&gt;Net20&lt;/TargetFramework&gt;
        ///  &lt;/ServiceItem&gt;
        ///&lt;/ArrayOfServiceItem&gt;.
        /// </summary>
        internal static string UncommitedInstalledServicesXmlFile {
            get {
                return ResourceManager.GetString("UncommitedInstalledServicesXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code is for run time compilation.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using System.ComponentModel;
        ///using System.Configuration.Install;
        ///using System.ServiceProcess;
        ///
        ///namespace CCNet.Common.Tests.Services1
        ///{
        ///	public static class Program
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// The main entry point for the application.
        ///		/// &lt;/summar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WindowsService1 {
            get {
                return ResourceManager.GetString("WindowsService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code is for run time compilation.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using System.ComponentModel;
        ///using System.Configuration.Install;
        ///using System.ServiceProcess;
        ///
        ///namespace CCNet.Common.Tests.Services2
        ///{
        ///	public static class Program
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// The main entry point for the application.
        ///		/// &lt;/summar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WindowsService2 {
            get {
                return ResourceManager.GetString("WindowsService2", resourceCulture);
            }
        }
    }
}
