//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNet.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCNet.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Running {0} has failed&lt;/b&gt;:&lt;br /&gt;{1}&lt;/p&gt;
        ///&lt;p&gt;&lt;i&gt;Please report Oleg Shuruev about this issue.&lt;/i&gt;&lt;/p&gt;.
        /// </summary>
        internal static string ExceptionHtml {
            get {
                return ResourceManager.GetString("ExceptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - found forbidden entry &quot;{0}&quot;.
        /// </summary>
        internal static string ForbiddenEntry {
            get {
                return ResourceManager.GetString("ForbiddenEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - property {0} is supposed to have value &quot;{1}&quot;, but now it is &quot;{2}&quot;.
        /// </summary>
        internal static string InvalidPropertyValue {
            get {
                return ResourceManager.GetString("InvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - missing required entry &quot;{0}&quot;.
        /// </summary>
        internal static string MissingRequiredEntry {
            get {
                return ResourceManager.GetString("MissingRequiredEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - missing required property {0}: &quot;{1}&quot;.
        /// </summary>
        internal static string MissingRequiredProperty {
            get {
                return ResourceManager.GetString("MissingRequiredProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service install process failed. Binary path: &quot;{0}&quot;..
        /// </summary>
        internal static string ServiceInstallError {
            get {
                return ResourceManager.GetString("ServiceInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service uninstall process failed. Binary path: &quot;{0}&quot;..
        /// </summary>
        internal static string ServiceUninstallError {
            get {
                return ResourceManager.GetString("ServiceUninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction file was not found..
        /// </summary>
        internal static string TransactionFileNotFound {
            get {
                return ResourceManager.GetString("TransactionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclosed transaction file was found. You cannot open another transaction before closing current..
        /// </summary>
        internal static string UnclosedTransactionFileFound {
            get {
                return ResourceManager.GetString("UnclosedTransactionFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - found unexpected entry &quot;{0}&quot;.
        /// </summary>
        internal static string UnexpectedEntry {
            get {
                return ResourceManager.GetString("UnexpectedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - found unexpected property {0}: &quot;{1}&quot;.
        /// </summary>
        internal static string UnexpectedProperty {
            get {
                return ResourceManager.GetString("UnexpectedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
